from tkinter import *
window=Tk()
window.geometry("900x800")
window.title("Distance Calculator")
window.config(bg="Light Grey")
def equationanswer():
    info=int(kmhentry.get()) * int(dshentry.get())
    answer.delete("1.0",END)
    answer.insert(END,info)
    
distant=Label(window,text="Distance Calculator",font=("Helvetica",60,"normal"),bg="light grey",fg="Beige")
distant.place(x=130,y=0)
kmh=Label(window,text="Kilometres Per Hour to destination:",font=("Helvetica",20,"normal"),bg="light grey")
kmh.place(x=50,y=100)
kmhentry=Entry(window,font=("Helvetica",20,"italic"),bg="beige")
kmhentry.place(x=500,y=100)
distancehour=Label(window,text="How many hours will it take to get there:",font=("Helvetica",20,"normal"),bg="light grey")
distancehour.place(x=50,y=200)
dshentry=Entry(window,font=("Helvetica",20,"normal"),bg="beige")
dshentry.place(x=570,y=200)
submit=Button(window,text="Submit",font=("Helvetica",20,"normal"),bg="green",command=equationanswer)
submit.place(x=250,y=300)
answerr=Label(window,text="Distance in km:",font=("Helvetica",20,"normal"),bg="light grey")
answer=Text(window,width=10,height=1,font=("Helvetica",20,"normal"),bg="beige")
answerr.place(x=50,y=400)
answer.place(x=280,y=400)
mainloop()