from tkinter import *
window=Tk()
window.geometry("800x600")
window.title("Finding your food enemy: part 1")
emailbox=Label(window,text="Email",font=("Helvetica",20,"bold"),bg="Light grey")
emailbox.place(x=100,y=40)
emailentre=Entry(window,font=("Helvetica",20,"bold"),bg="Light grey")
emailentre.place(x=230,y=40)
passwarden=Label(window,text="Password",font=("Helvetica",20,"bold"),bg="light grey",fg="dark green")
passwarden.place(x=100,y=100)
passwardene=Entry(window,font=("Helvetica",20,"bold"),bg="light grey")
passwardene.place(x=280,y=100)
whatfood=Label(window,text="Which food would you like? Fried Chicken (1), a Burger (2), Fries (3), a Pie (4) or none (5)?",font=("Helvetica",10,"bold"),bg="Light grey")
whatfooood=Entry(window,font=("Helvetica",20,"bold"),bg="Light grey")
whatfooooood=Spinbox(window,from_=1,to=5)
whatfood.place(x=100,y=160)
whatfooood.place(x=100,y=210)
whatfooooood.place(x=450,y=210)
whatbev=Label(window,text="What beverage would you like? Coca Cola (1), Pepsi (2), Fanta (3), Sprite (4), 7-Up (5), Mountain Dew (6), the unchallenged Fonta (7) or none (8)?",font=("Helvetica",7,"bold"),bg="Light grey")
whatbever=Entry(window,font=("Helvetica",20,"bold"),bg="Light grey")
whatbeverage=Spinbox(window,from_=1,to=8)
whatbev.place(x=100,y=280)
whatbever.place(x=100,y=350)
whatbeverage.place(x=450,y=350)
whatdes=Label(window,text="What dessert would you like? Ice Cream (1), an Ice Lolly (2), a Chocolate Cake (3) or none (4)?",font=("Helvetica",10,"bold"),bg="Light grey")
whatdesert=Entry(window,font=("Helvetica",20,"bold"),bg="Light grey")
whatdessertt=Spinbox(window,from_=1,to=4)
whatdes.place(x=100,y=420)
whatdesert.place(x=100,y=490)
whatdessertt.place(x=450,y=490)
submitttt=Button(window,text="Submit Order",font=("Helvetica",20,"bold"),bg="light grey")
submittery=Entry(window,font=("Helvetica",20,"bold italic"),bg="light grey")
submitttt.place(x=100,y=540)
submittery.place(x=320,y=540)



mainloop()