from tkinter import *
window=Tk()
#window.geometry("900x800")
window.title("Welcome to the histbox. Touch it, and you'll either get scratched and injured by a hostile cat or get $25 billion.")
scrollout=Scrollbar(window)
scrollout.pack(side=RIGHT,fill=Y)
listy=Listbox(window,height=10,width=250,fg="white",bg="brown",yscrollcommand=scrollout.set)
listy.insert(1,"Flying Broomstick - features a cannon and 6 AIM-7 missiles!")
listy.insert(2,"Flee Powder, sends you to a random place and the people living there have to flee from you!")
listy.insert(3,"The B-Jet - powered from 10 Firebolt Broomsticks, flies 920 Km/h with 80 passengers!")
listy.insert(4,"Malicious Mountain, grows from a tiny mound to a mountain and anyone who goes on it is turned into a chicken!")
listy.insert(5,"Fat Aircraft")
listy.insert(6,"Howler or GET OUT siren")
listy.insert(7,"Harness the power of a entity with the Imaadshah")
listy.insert(8,"yummy delicious hot cross bun")
listy.insert(9,"what")
listy.insert(10,"why")
listy.insert(11,"when")
listy.insert(12,"how")
listy.insert(13,"imaad")
listy.insert(14,"welcome to the hissbox")
listy.pack()
scrollout.config(command=listy.yview)


mainloop()