from tkinter import *
window=Tk()
window.title("IMT Imaad Paint")
window.geometry("900x800")
window.config(bg="Dark Green")
f1=Frame(window,bg="Green")
f1.pack(ipady=10)
pen=Button(f1,text="Pen",font=("Comic Sans MS",20,"italic"),bg="Dark Green",fg="White")
pen.grid(row=1,column=1,padx=10,pady=10)
brush=Button(f1,text="Brush",font=("Comic Sans MS",20,"normal"),bg="Dark Green",fg="white")
brush.grid(row=1,column=2,padx=10)
colour=Button(f1,text="Colour",font=("Comic Sans MS",20,"normal"),bg="Dark Green",fg="white")
colour.grid(row=1,column=3,padx=10)
eraser=Button(f1,text="Eraser",font=("Comic Sans MS",20,"normal"),bg="dark green",fg="white")
eraser.grid(row=1,column=4,padx=10)
clearall=Button(f1,text="Erase All",font=("Comic Sans MS",20,"normal"),bg="dark green",fg="white")
clearall.grid(row=1,column=5,padx=10)
#how do you make a slider
slider=Scale(f1,from_=1,to=10,orient=HORIZONTAL,bg="dark green",font=("Comic Sans MS",20,"normal"),fg="white")
slider.grid(row=1,column=6,padx=10)
f2=Frame(window,bg="white")
f2.pack(fill="both",expand=True)
paintonthecanvas=Canvas(f2,width=900,height=900,bg="Grey")
paintonthecanvas.pack()
mainloop()