from tkinter import *
from tkinter import messagebox

def description():
    r=thescentry.get()
    messagebox.showinfo("Thank you!",f"Feedback Form v1.0 - Created by {r}")
def allclear():
    thescentry.delete(0,END)
    rollersentrance.delete(0,END)
    danslaclasse.delete(0,END)
    therealessentialandtask.delete("1.0",END)
def exit():
    window.destroy()

window=Tk()
window.geometry("900x800")
window.title("Student Feedback forms, we want to see what students think the school should be like.")
files=Menu(window)
thechocolatefiles=Menu(files,tearoff=0)
files.add_cascade(label="File",menu=thechocolatefiles)
thechocolatefiles.add_command(label="New",command=allclear)
thechocolatefiles.add_separator()
thechocolatefiles.add_command(label="Exit",command=exit)
backerupper=Menu(files,tearoff=0)
files.add_cascade(label="Help",menu=backerupper)
backerupper.add_command(label="About",command=description)
studentname=Label(window,text="Student Name:",font=("Helvetica",20,"normal"),bg="red",fg="white")
studentname.place(x=0,y=30)
thescentry=Entry(window,font=("Helvetica",20,"normal"),bg="red",fg="white")
thescentry.place(x=320,y=30)
rollnumber=Label(window,text="Roll Number:",font=("Helvetica",20,"normal"),bg="dark green",fg="white")
rollnumber.place(x=0,y=140)
rollersentrance=Entry(window,font=("Helvetica",20,"normal"),bg="dark green",fg="white")
rollersentrance.place(x=320,y=140)
voicimasalledeclasse=Label(window,text="Class:",font=("Helvetica",20,"normal"),bg="Blue",fg="white")
voicimasalledeclasse.place(x=0,y=240)
danslaclasse=Entry(window,font=("Helvetica",20,"normal"),bg="blue",fg="white")
danslaclasse.place(x=320,y=240)
therealessentialandtask=Text(window,font=("Helvetica",20,"normal"),bg="Gold",fg="white",width=50,height=10)
therealessentialandtask.place(x=30,y=340)
mcvariable=StringVar()
excellent=Radiobutton(window,text="Excellent",font=("Helvetica",20,"normal"),bg="Green",variable=mcvariable,value="Excellent")
excellent.place(x=0,y=720)
good=Radiobutton(window,text="Good",font=("Helvetica",20,"normal"),bg="light green",variable=mcvariable,value="Good")
good.place(x=240,y=720)
average=Radiobutton(window,text="Average",font=("Helvetica",20,"normal"),bg="yellow",variable=mcvariable,value="Average")
average.place(x=480,y=720)
poor=Radiobutton(window,text="Poor",font=("Helvetica",20,"normal"),bg="dark red",variable=mcvariable,value="Good")
poor.place(x=720,y=720)
window.config(menu=files)
mainloop()