from tkinter import *
window=Tk()
window.geometry("900x800")
window.title("Chocolate Check - the first city")
window.config(bg="Green")
tickbox=Checkbutton(window,text="Do you eat chocolate?",bg="Yellow")
tickbox.place(x=450,y=400)
yum=Button(window,text="Welcome to the verfication of your chocolate rewards!",bg="Yellow")
yum.place(x=320,y=700)
nom=Label(window,text="What are you doing here?",bg="red")
nom.place(x=700,y=80)
neither=Entry(window,font=("Helvetica",20,"bold italic"),bg="White",fg="gray20",width=20)
neither.place(x=110,y=30)
mainloop()