from tkinter import *
window=Tk()
window.geometry("900x100")
window.config(bg="light grey")
window.title("Weight Converter - Imperial and Metric")
def fun_water():
    gram=int(kgentry.get()) * 1000
    pounds=int(kgentry.get()) * int(2.20462)
    ounces=int(kgentry.get()) * int(35.2739199982575)
    gramtry.delete("1.0",END)
    gramtry.insert(END,gram)
    powwww.delete("1.0",END)
    powwww.insert(END,pounds)
    ouncybouncy.delete("1.0",END)
    ouncybouncy.insert(END,ounces)
    

onceuponatime_enter_the_kg=Label(window,text="Enter the weight in Kg",font=("Helvetica",10,"italic"),fg="white",bg="black")
onceuponatime_enter_the_kg.place(x=20,y=0)
kgentry=Entry(window,font=("Arial",10,"bold"),fg="white",bg="grey")
kgentry.place(x=400,y=0)
convertte=Button(window,text="Convert",font=("Helvetica",10,"italic"),bg="light grey",command=fun_water)
convertte.place(x=760,y=0)
grammy=Label(window,text="Grams",font=("Times New Roman",10,"normal"),bg="light grey")
grammy.place(x=65,y=30)
whyimperialpounds=Label(window,text="Pounds",font=("Times New Roman",10,"normal"),bg="light grey")
whyimperialpounds.place(x=445,y=30)
ouchimperialounces=Label(window,text="Ounces",font=("Times New Roman",10,"normal"),bg="light grey")
ouchimperialounces.place(x=765,y=30)
gramtry=Text(window,font=("Helvetica",10,"normal"),width=20,height=1)
gramtry.place(x=20,y=60)
powwww=Text(window,font=("Helvetica",10,"normal"),width=20,height=1)
powwww.place(x=400,y=60)
ouncybouncy=Text(window,font=("Helvetica",10,"normal"),width=20,height=1)
ouncybouncy.place(x=715,y=60)
mainloop()